## Introducing ```numpy``` arrays

In [3]:
import os 
import numpy as np

In [4]:
# create file path (os is package, path is module and join is method)
filepath = os.path.join("..", "cds-vis-data", "data", "sample-data", "sample-data-01.csv") # the ".." means one step up in the working directory, i.e. from "session1_part2.ipynb" to cds-viz

In [5]:
filepath

'../cds-vis-data/data/sample-data/sample-data-01.csv'

In [6]:
data = np.loadtxt(fname=filepath, delimiter=",") 

In [7]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [8]:
type(data)

numpy.ndarray

In [9]:
data.dtype

dtype('float64')

In [10]:
data.shape # 60 rows, 40 columns

(60, 40)

In [ ]:
data[0,0] # the value in the first row of the first column

In [11]:
# array slice
data[0:4,0:10] # first 10 measurements of the first 4 rows 

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [12]:
# select whole row
data[0,:] # all values for row 0

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [13]:
# select whole column
data[:,0] # all values for column 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# average score
np.mean(data)

6.14875

In [15]:
np.max(data)

20.0

In [16]:
np.min(data)

0.0

In [17]:
np.max(data, axis=1) # maximum value along each row, i.e. for each patient


array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

In [ ]:
np.max(data, axis = 0) # maximum value along each column, i.e. per day